Repository arangodb/docs-hugo, pull requests merged in 2024-02, with the labels that each got.

#450 DOC-656 | Clarify AG org owner and member permissions
  site/content/3.10/arangograph/security-and-access-control/_index.md
  site/content/3.11/arangograph/security-and-access-control/_index.md
  site/content/3.12/arangograph/security-and-access-control/_index.md
Labels: cla-signed

#451 Remove ArangoGraph changelog
  site/content/3.10/arangograph/_index.md
  site/content/3.10/arangograph/changelog.md
  site/content/3.11/arangograph/_index.md
  site/content/3.11/arangograph/changelog.md
  site/content/3.12/arangograph/_index.md
  site/content/3.12/arangograph/changelog.md
Labels: cla-signed

#457 DOC-614 | BTS-1661 - Different errors for vertex collection not in graph
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
Labels: cla-signed

#419 DOC-624 | Add ArangoML self-managed content
  site/content/3.10/data-science/arangographml/_index.md
  site/content/3.10/data-science/arangographml/deploy.md
  site/content/3.10/data-science/arangographml/getting-started.md
  site/content/3.10/data-science/graphml/getting-started-with-arangographml.md
  site/content/3.11/data-science/arangographml/_index.md
  site/content/3.11/data-science/arangographml/deploy.md
  site/content/3.11/data-science/arangographml/getting-started.md
  site/content/3.11/data-science/graphml/getting-started-with-arangographml.md
  site/content/3.12/data-science/arangographml/_index.md
  site/content/3.12/data-science/arangographml/deploy.md
  site/content/3.12/data-science/arangographml/getting-started.md
  site/content/3.12/data-science/graphml/getting-started-with-arangographml.md
  site/content/images/ArangoML_open_intelligence_sample.png
  site/content/images/ArangoML_open_intelligence_visualization.png
Labels: cla-signed

#447 DOC-614 | Add behavior change when dropping a collection from a graph
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
Labels: cla-signed

#459 DOC-614 | Changed startup option defaults, audit log escaping, cluster compaction
  site/content/3.11/release-notes/version-3.11/whats-new-in-3-11.md
  site/content/3.12/release-notes/version-3.11/whats-new-in-3-11.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#458 DOC-614 | Remove VelocyStream
  site/content/3.12/about-arangodb/features/highlights-by-version.md
  site/content/3.12/components/tools/arangodb-shell/examples.md
  site/content/3.12/develop/http-api/administration.md
  site/content/3.12/develop/http-api/general-request-handling.md
  site/content/3.12/release-notes/deprecated-and-removed-features.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed, 9 Ready to Merge

#408 DOC-614 | Release notes: Query editor options & optimizer rules
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#460 DOC-614 | Remove Pregel
  site/content/3.10/aql/functions/miscellaneous.md
  site/content/3.10/aql/graphs/_index.md
  site/content/3.10/components/tools/arangobackup/_index.md
  site/content/3.10/components/web-interface/users.md
  site/content/3.10/deploy/in-the-cloud.md
  site/content/3.10/deploy/oneshard.md
  site/content/3.10/develop/http-api/transactions/stream-transactions.md
  site/content/3.10/graphs/_index.md
  site/content/3.10/index-and-search/arangosearch/fuzzy-search.md
  site/content/3.10/release-notes/deprecated-and-removed-features.md
  site/content/3.11/aql/functions/miscellaneous.md
  site/content/3.11/aql/graphs/_index.md
  site/content/3.11/components/tools/arangobackup/_index.md
  site/content/3.11/components/web-interface/users.md
  site/content/3.11/deploy/in-the-cloud.md
  site/content/3.11/deploy/oneshard.md
  site/content/3.11/develop/http-api/transactions/stream-transactions.md
  site/content/3.11/graphs/_index.md
  site/content/3.11/index-and-search/arangosearch/fuzzy-search.md
  site/content/3.11/release-notes/deprecated-and-removed-features.md
  site/content/3.12/about-arangodb/features/_index.md
  site/content/3.12/about-arangodb/features/community-edition.md
  site/content/3.12/about-arangodb/features/enterprise-edition.md
  site/content/3.12/about-arangodb/features/highlights-by-version.md
  site/content/3.12/aql/functions/miscellaneous.md
  site/content/3.12/aql/graphs/_index.md
  site/content/3.12/components/tools/arangobackup/_index.md
  site/content/3.12/components/web-interface/users.md
  site/content/3.12/concepts/data-models.md
  site/content/3.12/concepts/data-structure/documents/computed-values.md
  site/content/3.12/data-science/_index.md
  site/content/3.12/data-science/adapters/arangodb-networkx-adapter.md
  site/content/3.12/data-science/arangographml/_index.md
  site/content/3.12/data-science/pregel/_index.md
  site/content/3.12/data-science/pregel/algorithms.md
  site/content/3.12/deploy/in-the-cloud.md
  site/content/3.12/deploy/oneshard.md
  site/content/3.12/develop/http-api/administration.md
  site/content/3.12/develop/http-api/general-request-handling.md
  site/content/3.12/develop/http-api/monitoring/logs.md
  site/content/3.12/develop/http-api/pregel.md
  site/content/3.12/develop/http-api/transactions/stream-transactions.md
  site/content/3.12/develop/javascript-api/_index.md
  site/content/3.12/graphs/_index.md
  site/content/3.12/graphs/example-graphs.md
  site/content/3.12/index-and-search/arangosearch/fuzzy-search.md
  site/content/3.12/release-notes/deprecated-and-removed-features.md
  site/content/3.12/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.12/release-notes/version-3.11/api-changes-in-3-11.md
  site/content/3.12/release-notes/version-3.11/whats-new-in-3-11.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.7/whats-new-in-3-7.md
Labels: cla-signed

#452 DOC-658 | Set to draft Cloud Migration Tool and remove associated references
  site/content/3.10/arangograph/data-loader/_index.md
  site/content/3.10/arangograph/migrate-to-the-cloud.md
  site/content/3.10/get-started/_index.md
  site/content/3.10/release-notes/deprecated-and-removed-features.md
  site/content/3.11/arangograph/data-loader/_index.md
  site/content/3.11/arangograph/migrate-to-the-cloud.md
  site/content/3.11/get-started/_index.md
  site/content/3.11/release-notes/deprecated-and-removed-features.md
  site/content/3.12/arangograph/data-loader/_index.md
  site/content/3.12/arangograph/migrate-to-the-cloud.md
  site/content/3.12/get-started/_index.md
  site/content/3.12/release-notes/deprecated-and-removed-features.md
  site/content/images/arangograph-data-loader-migration-use-cases.png
  toolchain/scripts/start_hugo.sh
Labels: cla-signed

#462 DOC-614 | Add release notes: compression for cluster-internal traffic
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#468 DOC-662 | Version upgrades in ArangoGraph
  site/content/3.10/arangograph/deployments/upgrades-and-versioning.md
  site/content/3.11/arangograph/deployments/upgrades-and-versioning.md
  site/content/3.12/arangograph/deployments/upgrades-and-versioning.md
Labels: cla-signed

#469 DOC-614 | Batch materialize with projections
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#456 Render accepted HTTP headers, explain API basics
  site/content/3.10/develop/http-api/_index.md
  site/content/3.10/develop/http-api/collections.md
  site/content/3.10/develop/http-api/documents.md
  site/content/3.10/develop/http-api/graphs/named-graphs.md
  site/content/3.10/develop/http-api/transactions/stream-transactions.md
  site/content/3.11/develop/http-api/_index.md
  site/content/3.11/develop/http-api/collections.md
  site/content/3.11/develop/http-api/documents.md
  site/content/3.11/develop/http-api/graphs/named-graphs.md
  site/content/3.11/develop/http-api/transactions/stream-transactions.md
  site/content/3.12/develop/http-api/_index.md
  site/content/3.12/develop/http-api/collections.md
  site/content/3.12/develop/http-api/documents.md
  site/content/3.12/develop/http-api/graphs/named-graphs.md
  site/content/3.12/develop/http-api/transactions/stream-transactions.md
  site/themes/arangodb-docs-theme/layouts/_default/_markup/render-codeblock-openapi.html
Labels: cla-signed

#472 DOC-663 | Add missing info on autologin feature and private endpoints in AG
  site/content/3.10/arangograph/deployments/_index.md
  site/content/3.11/arangograph/deployments/_index.md
  site/content/3.12/arangograph/deployments/_index.md
Labels: cla-signed

#461 Pre-wrap more code to avoid layout overflow
  site/themes/arangodb-docs-theme/static/css/theme.css
Labels: cla-signed

#465 DOC-614 | Adjustable writeConcern
  site/content/3.10/develop/http-api/collections.md
  site/content/3.10/develop/http-api/databases.md
  site/content/3.10/develop/javascript-api/@arangodb/collection-object.md
  site/content/3.10/develop/javascript-api/@arangodb/db-object.md
  site/content/3.11/develop/http-api/collections.md
  site/content/3.11/develop/http-api/databases.md
  site/content/3.11/develop/javascript-api/@arangodb/collection-object.md
  site/content/3.11/develop/javascript-api/@arangodb/db-object.md
  site/content/3.12/develop/http-api/collections.md
  site/content/3.12/develop/http-api/databases.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
Labels: cla-signed

#463 DOC-659 | Remove LDAP
  site/content/3.12/about-arangodb/features/_index.md
  site/content/3.12/about-arangodb/features/enterprise-edition.md
  site/content/3.12/about-arangodb/features/highlights-by-version.md
  site/content/3.12/components/arangodb-server/ldap.md
  site/content/3.12/develop/http-api/monitoring/logs.md
  site/content/3.12/get-started/set-up-a-cloud-instance.md
  site/content/3.12/operations/administration/user-management/_index.md
  site/content/3.12/operations/administration/user-management/in-arangosh.md
  site/content/3.12/operations/installation/compiling/compile-on-debian.md
  site/content/3.12/release-notes/deprecated-and-removed-features.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.2/whats-new-in-3-2.md
  site/content/3.12/release-notes/version-3.3/whats-new-in-3-3.md
Labels: cla-signed

#453 DOC-614 | Versioning support for document operations
  site/content/3.12/about-arangodb/features/highlights-by-version.md
  site/content/3.12/aql/high-level-operations/insert.md
  site/content/3.12/aql/high-level-operations/replace.md
  site/content/3.12/aql/high-level-operations/update.md
  site/content/3.12/develop/http-api/documents.md
  site/content/3.12/develop/javascript-api/@arangodb/collection-object.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#471 DOC-627 | RocksDB reserve memory in block cache
  site/content/3.10/components/arangodb-server/storage-engine.md
  site/content/3.11/components/arangodb-server/storage-engine.md
  site/content/3.12/components/arangodb-server/storage-engine.md
  site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed, 9 Ready to Merge

#478 remove mentions of active failover delpoyment in 3.12
  site/content/3.12/develop/drivers/java/reference-version-6/driver-setup.md
  site/content/3.12/develop/drivers/java/reference-version-7/driver-setup.md
  site/content/3.12/develop/integrations/arangodb-datasource-for-apache-spark.md
Labels: cla-signed

#475 DOC-654 | AQL Limit operation and sorting
  site/content/3.10/aql/high-level-operations/for.md
  site/content/3.10/aql/high-level-operations/limit.md
  site/content/3.10/aql/high-level-operations/sort.md
  site/content/3.11/aql/high-level-operations/for.md
  site/content/3.11/aql/high-level-operations/limit.md
  site/content/3.11/aql/high-level-operations/sort.md
  site/content/3.12/aql/high-level-operations/for.md
  site/content/3.12/aql/high-level-operations/limit.md
  site/content/3.12/aql/high-level-operations/sort.md
Labels: cla-signed

#426 DOC-648 | Stable multi-dimensional indexes
  site/content/3.10/develop/http-api/indexes/fulltext.md
  site/content/3.10/develop/http-api/indexes/geo-spatial.md
  site/content/3.10/develop/http-api/indexes/multi-dimensional.md
  site/content/3.10/develop/http-api/indexes/ttl.md
  site/content/3.10/develop/http-api/replication/other-replication-commands.md
  site/content/3.10/index-and-search/indexing/working-with-indexes/multi-dimensional-indexes.md
  site/content/3.10/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.11/develop/http-api/indexes/fulltext.md
  site/content/3.11/develop/http-api/indexes/geo-spatial.md
  site/content/3.11/develop/http-api/indexes/inverted.md
  site/content/3.11/develop/http-api/indexes/multi-dimensional.md
  site/content/3.11/develop/http-api/indexes/ttl.md
  site/content/3.11/develop/http-api/replication/other-replication-commands.md
  site/content/3.11/index-and-search/indexing/working-with-indexes/multi-dimensional-indexes.md
  site/content/3.11/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.11/release-notes/version-3.11/api-changes-in-3-11.md
  site/content/3.12/about-arangodb/features/community-edition.md
  site/content/3.12/about-arangodb/features/highlights-by-version.md
  site/content/3.12/aql/high-level-operations/for.md
  site/content/3.12/develop/http-api/indexes/fulltext.md
  site/content/3.12/develop/http-api/indexes/geo-spatial.md
  site/content/3.12/develop/http-api/indexes/inverted.md
  site/content/3.12/develop/http-api/indexes/multi-dimensional.md
  site/content/3.12/develop/http-api/indexes/persistent.md
  site/content/3.12/develop/http-api/indexes/ttl.md
  site/content/3.12/develop/http-api/replication/other-replication-commands.md
  site/content/3.12/index-and-search/indexing/basics.md
  site/content/3.12/index-and-search/indexing/which-index-to-use-when.md
  site/content/3.12/index-and-search/indexing/working-with-indexes/_index.md
  site/content/3.12/index-and-search/indexing/working-with-indexes/multi-dimensional-indexes.md
  site/content/3.12/index-and-search/indexing/working-with-indexes/vertex-centric-indexes.md
  site/content/3.12/operations/administration/telemetrics.md
  site/content/3.12/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.12/release-notes/version-3.11/api-changes-in-3-11.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
  site/data/3.12/cache.json
Labels: 9 Ready to Merge
