Repository arangodb/docs-hugo, pull requests merged in 2024-01, with the labels that each got.

#407 Add download link to Data Loader example files
  site/content/3.10/arangograph/data-loader/example.md
  site/content/3.11/arangograph/data-loader/example.md
  site/content/3.12/arangograph/data-loader/example.md
Labels: cla-signed

#401 Added `arangodb_aql_cursors_memory_usage` metric to memory accounting list
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#402 Remove async replication content that is AF specific (3.12 only)
  site/content/3.12/deploy/architecture/replication.md
Labels: cla-signed

#403 DOC-626 | Move storage engine content under ArangoDB Server
  site/content/3.10/about-arangodb/features/community-edition.md
  site/content/3.10/about-arangodb/features/highlights-by-version.md
  site/content/3.10/about-arangodb/use-cases.md
  site/content/3.10/components/arangodb-server/storage-engine.md
  site/content/3.10/deploy/architecture/_index.md
  site/content/3.10/develop/transactions/limitations.md
  site/content/3.10/release-notes/version-3.6/incompatible-changes-in-3-6.md
  site/content/3.11/about-arangodb/features/community-edition.md
  site/content/3.11/about-arangodb/features/highlights-by-version.md
  site/content/3.11/about-arangodb/use-cases.md
  site/content/3.11/components/arangodb-server/storage-engine.md
  site/content/3.11/deploy/architecture/_index.md
  site/content/3.11/develop/transactions/limitations.md
  site/content/3.11/release-notes/version-3.6/incompatible-changes-in-3-6.md
  site/content/3.12/about-arangodb/features/community-edition.md
  site/content/3.12/about-arangodb/features/highlights-by-version.md
  site/content/3.12/about-arangodb/use-cases.md
  site/content/3.12/components/arangodb-server/storage-engine.md
  site/content/3.12/deploy/architecture/_index.md
  site/content/3.12/develop/transactions/limitations.md
  site/content/3.12/release-notes/version-3.6/incompatible-changes-in-3-6.md
Labels: cla-signed

#414 [DE-619] Kafka Connector: removed limitation about VST
  site/content/3.10/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
  site/content/3.11/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
  site/content/3.12/develop/integrations/kafka-connect-arangodb-sink-connector/_index.md
Labels: cla-signed

#412 DOC-614 | Protocol aliases for endpoints
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: 9 Waiting for Upstream Merge, cla-signed

#417 DOC-647 | Clarify the presence of `nextBatchId`
  site/content/3.11/develop/http-api/queries/aql-queries.md
  site/content/3.12/develop/http-api/queries/aql-queries.md
Labels: cla-signed

#416 Separate folder and mount for static files (Netlify _redirects)
  README.md
  site/config/_default/config.yaml
  site/static/_redirects
Labels: cla-signed

#409 DOC-614 | Added `readOwnWrites` option for UPSERT operations
  site/content/3.12/aql/high-level-operations/upsert.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#418 Release notes: Improved `move-filters-into-enumerate` optimizer rule
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#424 DOC-614 | Some arangod exit codes changed
  site/content/3.10/release-notes/version-3.10/incompatible-changes-in-3-10.md
  site/content/3.11/release-notes/version-3.11/incompatible-changes-in-3-11.md
  site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
Labels: cla-signed

#421 DOC-614 | Mention extended edge update validation in Gharial
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
Labels: cla-signed

#425 DOC-614 | Add Options API
  site/content/3.12/develop/http-api/administration.md
  site/content/3.12/operations/administration/configuration.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#410 DOC-614 | Async prefetching AQL optimizer rule
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#427 Do not debug-dump for top-level arrays & improve array rendering in OpenAPI responses
  site/themes/arangodb-docs-theme/layouts/_default/_markup/render-codeblock-openapi.html
Labels: cla-signed

#432 Improve lead paragraphs of the AQL UPDATE and REPLACE operations
  site/content/3.10/aql/high-level-operations/replace.md
  site/content/3.10/aql/high-level-operations/update.md
  site/content/3.11/aql/high-level-operations/replace.md
  site/content/3.11/aql/high-level-operations/update.md
  site/content/3.12/aql/high-level-operations/replace.md
  site/content/3.12/aql/high-level-operations/update.md
Labels: cla-signed

#433 Release notes: Detached scheduler threads
  site/content/3.10/release-notes/version-3.10/whats-new-in-3-10.md
  site/content/3.11/release-notes/version-3.10/whats-new-in-3-10.md
  site/content/3.11/release-notes/version-3.11/whats-new-in-3-11.md
  site/content/3.12/release-notes/version-3.10/whats-new-in-3-10.md
  site/content/3.12/release-notes/version-3.11/whats-new-in-3-11.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#431 DOC-614 | V8 upgrade to v12
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#430 Spring Data: added documentation to customize auditing
  site/content/3.10/develop/integrations/spring-data-arangodb/reference-version-3/mapping/auditing.md
  site/content/3.10/develop/integrations/spring-data-arangodb/reference-version-4/mapping/auditing.md
  site/content/3.11/develop/integrations/spring-data-arangodb/reference-version-3/mapping/auditing.md
  site/content/3.11/develop/integrations/spring-data-arangodb/reference-version-4/mapping/auditing.md
  site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-3/mapping/auditing.md
  site/content/3.12/develop/integrations/spring-data-arangodb/reference-version-4/mapping/auditing.md
Labels: cla-signed

#376 DOC-592 | Improved joins
  site/content/3.12/aql/examples-and-query-patterns/joins.md
  site/content/3.12/aql/execution-and-performance/query-optimization.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#382 DOC-635 | Multiple delimiters Analyzer
  site/content/3.12/index-and-search/analyzers.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
  site/data/3.12/cache.json
Labels: 9 Ready to Merge

#436 Add `smartGraphAttribute` validation behavior change
  site/content/3.10/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.10/release-notes/version-3.10/incompatible-changes-in-3-10.md
  site/content/3.11/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.11/release-notes/version-3.10/incompatible-changes-in-3-10.md
  site/content/3.11/release-notes/version-3.11/api-changes-in-3-11.md
  site/content/3.11/release-notes/version-3.11/incompatible-changes-in-3-11.md
  site/content/3.12/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.12/release-notes/version-3.10/incompatible-changes-in-3-10.md
  site/content/3.12/release-notes/version-3.11/api-changes-in-3-11.md
  site/content/3.12/release-notes/version-3.11/incompatible-changes-in-3-11.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/incompatible-changes-in-3-12.md
Labels: cla-signed

#435 DOC-643 | Adjust Data Loader content and screenshots
  site/content/3.10/arangograph/data-loader/_index.md
  site/content/3.10/arangograph/data-loader/design-graph.md
  site/content/3.10/arangograph/data-loader/example.md
  site/content/3.11/arangograph/data-loader/_index.md
  site/content/3.11/arangograph/data-loader/design-graph.md
  site/content/3.11/arangograph/data-loader/example.md
  site/content/3.12/arangograph/data-loader/_index.md
  site/content/3.12/arangograph/data-loader/design-graph.md
  site/content/3.12/arangograph/data-loader/example.md
  site/content/images/arangograph-data-loader-example-choose-names.png
  site/content/images/arangograph-data-loader-example-map-edges.png
  site/content/images/arangograph-data-loader-example-map-nodes.png
  site/content/images/arangograph-data-loader-migration-use-cases.png
Labels: cla-signed

#438 DOC-614 | Progress indication for index generation
  site/content/3.10/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.11/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.11/release-notes/version-3.11/api-changes-in-3-11.md
  site/content/3.12/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.12/release-notes/version-3.11/api-changes-in-3-11.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
Labels: cla-signed

#429 DOC-614 | Per collection/database/user monitoring
  site/content/3.10/develop/http-api/monitoring/metrics.md
  site/content/3.10/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.10/release-notes/version-3.10/whats-new-in-3-10.md
  site/content/3.11/develop/http-api/monitoring/metrics.md
  site/content/3.11/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.11/release-notes/version-3.10/whats-new-in-3-10.md
  site/content/3.11/release-notes/version-3.11/api-changes-in-3-11.md
  site/content/3.11/release-notes/version-3.11/whats-new-in-3-11.md
  site/content/3.12/develop/http-api/monitoring/metrics.md
  site/content/3.12/release-notes/version-3.10/api-changes-in-3-10.md
  site/content/3.12/release-notes/version-3.10/whats-new-in-3-10.md
  site/content/3.12/release-notes/version-3.11/api-changes-in-3-11.md
  site/content/3.12/release-notes/version-3.11/whats-new-in-3-11.md
  site/content/3.12/release-notes/version-3.12/api-changes-in-3-12.md
  site/content/3.12/release-notes/version-3.12/whats-new-in-3-12.md
Labels: cla-signed

#440 add specification hyperlinks
  site/content/3.10/data-science/arangographml/getting-started.md
  site/content/3.11/data-science/arangographml/getting-started.md
  site/content/3.12/data-science/arangographml/getting-started.md
Labels: cla-signed

#441 [DE-707] Spring Data: documented configuration for VPACK content type
  site/content/3.10/develop/integrations/spring-data-arangodb/_index.md
  site/content/3.11/develop/integrations/spring-data-arangodb/_index.md
  site/content/3.12/develop/integrations/spring-data-arangodb/_index.md
Labels: cla-signed

#439 ArangoRDF Updates
  site/content/3.10/data-science/adapters/_index.md
  site/content/3.10/data-science/adapters/arangodb-rdf-adapter.md
  site/content/3.10/data-science/adapters/arangordf-adapter/_index.md
  site/content/3.10/data-science/adapters/arangordf-adapter/mapping-rdf-to-graphs.md
  site/content/3.11/data-science/adapters/_index.md
  site/content/3.11/data-science/adapters/arangodb-rdf-adapter.md
  site/content/3.11/data-science/adapters/arangordf-adapter/_index.md
  site/content/3.11/data-science/adapters/arangordf-adapter/mapping-rdf-to-graphs.md
  site/content/3.12/data-science/adapters/_index.md
  site/content/3.12/data-science/adapters/arangodb-rdf-adapter.md
  site/content/3.12/data-science/adapters/arangordf-adapter/_index.md
  site/content/3.12/data-science/adapters/arangordf-adapter/mapping-rdf-to-graphs.md
Labels: cla-signed

#444 fix ArangoRDF typo
  site/content/3.10/data-science/adapters/arangodb-rdf-adapter.md
  site/content/3.11/data-science/adapters/arangodb-rdf-adapter.md
  site/content/3.12/data-science/adapters/arangodb-rdf-adapter.md
Labels: cla-signed

#445 nit: cleanup adapter references
  site/content/3.10/data-science/adapters/_index.md
  site/content/3.10/data-science/adapters/arangodb-cugraph-adapter.md
  site/content/3.10/data-science/adapters/arangodb-dgl-adapter.md
  site/content/3.10/data-science/adapters/arangodb-networkx-adapter.md
  site/content/3.10/data-science/adapters/arangodb-pyg-adapter.md
  site/content/3.10/data-science/adapters/arangodb-rdf-adapter.md
  site/content/3.11/data-science/adapters/_index.md
  site/content/3.11/data-science/adapters/arangodb-cugraph-adapter.md
  site/content/3.11/data-science/adapters/arangodb-dgl-adapter.md
  site/content/3.11/data-science/adapters/arangodb-networkx-adapter.md
  site/content/3.11/data-science/adapters/arangodb-pyg-adapter.md
  site/content/3.11/data-science/adapters/arangodb-rdf-adapter.md
  site/content/3.12/data-science/adapters/_index.md
  site/content/3.12/data-science/adapters/arangodb-cugraph-adapter.md
  site/content/3.12/data-science/adapters/arangodb-dgl-adapter.md
  site/content/3.12/data-science/adapters/arangodb-networkx-adapter.md
  site/content/3.12/data-science/adapters/arangodb-pyg-adapter.md
  site/content/3.12/data-science/adapters/arangodb-rdf-adapter.md
Labels: cla-signed

#446 DOC-649 | Disable ToC scroll into view, throttle scroll events
  site/themes/arangodb-docs-theme/static/js/theme.js
Labels: cla-signed
